### ISSUE TITLE
Error when training on Pong in Colab

### ISSUE THREAD

**Issue by robjlyons** [danijar/dreamerv3#10]
I am trying this in Google Colab on a CPU instance so please let me know if this is not possible?

I installed DreamerV3 using:

```
!pip install dreamerv3
```

Then copied the example.py file with a couple of changes:
```
import warnings
import dreamerv3
from dreamerv3 import embodied
warnings.filterwarnings('ignore', '.*truncated to dtype int32.*')

# See configs.yaml for all options.
config = embodied.Config(dreamerv3.configs['defaults'])
config = config.update(dreamerv3.configs['small'])
config = config.update({
    'logdir': '~/logdir/run3',
    'run.train_ratio': 64,
    'run.eval_eps': 10,
    'run.log_every': 30,  # Seconds
    'batch_size': 16,
    'jax.prealloc': False,
    'encoder.mlp_keys': '$^',
    'decoder.mlp_keys': '$^',
    'encoder.cnn_keys': 'image',
    'decoder.cnn_keys': 'image',
    'jax.platform': 'cpu',
})
config = embodied.Flags(config).parse()

logdir = embodied.Path(config.logdir)
step = embodied.Counter()
logger = embodied.Logger(step, [
    embodied.logger.TerminalOutput(),
    embodied.logger.JSONLOutput(logdir, 'metrics.jsonl'),
    embodied.logger.TensorBoardOutput(logdir),
    # embodied.logger.WandBOutput(logdir.name, config),
    # embodied.logger.MLFlowOutput(logdir.name),
])

import gym
from embodied.envs import from_gym
from gym.wrappers import ResizeObservation
env = gym.make("PongNoFrameskip-v4")  # Replace this with your Gym env.
env = ResizeObservation(env, 128)
env = from_gym.FromGym(env)
env = dreamerv3.wrap_env(env, config)
env = embodied.BatchEnv([env], parallel=False)

agent = dreamerv3.Agent(env.obs_space, env.act_space, step, config)
replay = embodied.replay.Uniform(
    config.batch_length, config.replay_size, logdir / 'replay')
args = embodied.Config(
    **config.run, logdir=config.logdir,
    batch_steps=config.batch_size * config.batch_length)
embodied.run.train(agent, env, replay, logger, args)
```

The error I receive seems to be linked to the line:
```
config = embodied.Flags(config).parse()
```
The error is:

Traceback (most recent call last)
in <module>  /usr/local/lib/python3.8/dist-packages/dreamerv3/embodied/core/flags.py:17 in parse 
 for flag in remaining: 
if flag.startswith('--'):
raise ValueError(f"Flag '{flag}' did not match any config keys.")
assert not remaining, remaining
return parsed
def parse_known(self, argv=None, help_exists=False):

AssertionError: ['-f', '/root/.local/share/jupyter/runtime/kernel-0d0baf68-d3f6-463e-b3c8-d0320085b92e.json']

I did try commenting out the config line but then received the following error:

Traceback (most recent call last)
in <module>  /usr/local/lib/python3.8/dist-packages/dreamerv3/embodied/run/train.py:106 in train

policy = lambda *args: agent.policy(*args, mode='explore' if should_expl(step) else 'train')
while step < args.steps:
     driver(policy, steps=100)
     if should_save(step):
          checkpoint.save()
          logger.write() 

/usr/local/lib/python3.8/dist-packages/dreamerv3/embodied/core/driver.py:42 in __call__

def __call__(self, policy, steps=0, episodes=0):
     step, episode = 0, 0
     while step < steps or episode < episodes:
          step, episode = self._step(policy, step, episode)
def _step(self, policy, step, episode):
     assert all(len(x) == len(self._env) for x in self._acts.values())

/usr/local/lib/python3.8/dist-packages/dreamerv3/embodied/core/driver.py:65 in _step

for i in range(len(self._env)):
     trn = {k: v[i] for k, v in trns.items()}
     [self._eps[i][k].append(v) for k, v in trn.items()]
     [fn(trn, i, **self._kwargs) for fn in self._on_steps]
     step += 1
     if obs['is_last'].any():
          for i, done in enumerate(obs['is_last']):

/usr/local/lib/python3.8/dist-packages/dreamerv3/embodied/core/driver.py:65 in <listcomp>

for i in range(len(self._env)):
     trn = {k: v[i] for k, v in trns.items()}
     [self._eps[i][k].append(v) for k, v in trn.items()]
     [fn(trn, i, **self._kwargs) for fn in self._on_steps]
     step += 1
     if obs['is_last'].any():
          for i, done in enumerate(obs['is_last']):

/usr/local/lib/python3.8/dist-packages/dreamerv3/embodied/run/train.py:75 in train_step
     for _ in range(should_train(step)):
          with timer.scope('dataset'):
               batch[0] = next(dataset)
               outs, state[0], mets = agent.train(batch[0], state[0])
               metrics.add(mets, prefix='train')
               if 'priority' in outs:
                    replay.prioritize(outs['key'], outs['priority'])

/usr/lib/python3.8/contextlib.py:75 in inner

@wraps(func)
def inner(*args, **kwds):
     with self._recreate_cm():
          return func(*args, **kwds)
     return inner

/usr/local/lib/python3.8/dist-packages/dreamerv3/jaxagent.py:76 in train

self._once = False
assert jaxutils.Optimizer.PARAM_COUNTS
for name, count in jaxutils.Optimizer.PARAM_COUNTS.items():
     mets[f'params_{name}'] = float(count)
     return outs, state, mets

def report(self, data):

TypeError: float() argument must be a string or a number, not 'NoneType'

Hopefully I have provided enough information. I'll be happy to provide more if needed.

Thanks,

**Comment by danijar** [comment]
Thanks for the report. Can you run `pip freeze` to make sure you're using `dreamerv3==1.4.0`?

**Comment by robjlyons** [comment]
I am indeed running dreamerv3==1.4.0. The restart fixed the issue and now I have the example working with Pong. Thank you
