### ISSUE TITLE
Ask about jit in ninjax.py

### ISSUE THREAD

**Issue by realjoenguyen** [danijar/dreamerv3#100]
Hi, 

As I am a beginner in jax, may I ask why you need to re-define `jit` in ninjax.py ([here](https://github.com/danijar/dreamerv3/blob/8fa35f83eee1ce7e10f3dee0b766587d0a713a60/dreamerv3/ninjax.py#L174)) ? 

Is it because you need to return state in your jit? 
Sorry for a seemingly dumb question!  
Thank you in advance!

**Comment by danijar** [comment]
Just updated the code, which removes `nj.jit`.
