### ISSUE TITLE
Hybrid Action Spaces

### ISSUE THREAD

**Issue by Pippo809** [danijar/dreamerv3#107]
Hey @danijar , first of all thank you very much for the wonderful work.
I'm currently implementing the work in an environment with hybrid action spaces (IE both continuous and discrete actions), I've tried discretizing the continuous actions and it works. 

However I am trying now to adapt the Critic network to include a multi-headed output for both action distribution (Categorical and Continuous), I am struggling a bit to adapt the world model accordingly tho, do you have any suggestions on how to act?

Many thanks in advance.

**Comment by danijar** [comment]
How about one hot encoding the discrete action and concatenating with the continuous one?

**Comment by Pippo809** [comment]
I'm not completely sure about what you mean by one-hot encoding, wouldn't the output of the network still be a continuous value (sampled from whatever distribution)?

You mean that I could have [cont_action_1, cont_action_2, ..., disc_action_1, disc_action_2, ..., #num_discrete_actions] as action space and when applying the action just choose the discrete one with the highest value?

Many thanks again for the support!

**Comment by Pippo809** [comment]
I have implemented a [rudimentary version of hybrid model trough multi-headed output ](https://github.com/Pippo809/dreamerv3)from the actor critic, I still have to test it troughly to evaluate its performance.

**Comment by danijar** [comment]
Just updated the code and results, which includes factorized action spaces.
