### ISSUE TITLE
RNG splitting

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [danijar/dreamerv3#11]
https://github.com/danijar/dreamerv3/blob/688e04fc0b7779d51bbc4fe93569f6c923e24239/dreamerv3/jaxutils.py#L31

Unless im misunderstanding the intent here, should that not be :
``` self.buffer = self.buffer[amount:] ```

**Comment by danijar** [comment]
Good catch! I think you're right. I'll run some experiments to see if it makes a difference.

**Comment by danijar** [comment]
Fixed in the newest commit. I didn't notice any significant difference in practice.
