### ISSUE TITLE
train.py make_envs error: tuple index out of range in cloudpickle.py

### ISSUE THREAD

**Issue by kennetms** [danijar/dreamerv3#112]
I can run example.py fine but when I run train.py then I get an error in cloudpickle.py from the make_envs function.

I'm using Ubuntu 20.04, Python3.11

python dreamerv3/train.py  --logdir ~/logdir/$(date "+%Y%m%d-%H%M%S")  --configs crafter --batch_size 16 --run.train_ratio 32

train.py:153 in <listcomp>                                │
│                                                                                                  │
│   150 │   if config.envs.restart:                                                                │
│   151 │     ctor = bind(wrappers.RestartOnException, ctor)                                       │
│   152 │   ctors.append(ctor)                                                                     │
│ ❱ 153   envs = [ctor() for ctor in ctors] 

cloudpickle.py:23 │
│ 6 in <setcomp>                                                                                   │
│                                                                                                  │
│   233 │   out_names = _extract_code_globals_cache.get(co)                                        │
│   234 │   if out_names is None:                                                                  │
│   235 │   │   names = co.co_names                                                                │
│ ❱ 236 │   │   out_names = {names[oparg] for _, oparg in _walk_global_ops(co)}

IndexError: tuple index out of range

Here is my pip list:
Package                      Version
---------------------------- ---------------------
absl-py                      2.1.0
astunparse                   1.6.3
certifi                      2024.2.2
charset-normalizer           3.3.2
chex                         0.1.85
cloudpickle                  1.6.0
crafter                      1.8.3
decorator                    5.1.1
dm-tree                      0.1.8
flatbuffers                  24.3.7
gast                         0.5.4
google-pasta                 0.2.0
grpcio                       1.62.1
gym                          0.19.0
h5py                         3.10.0
idna                         3.6
imageio                      2.34.0
jax                          0.4.25
jaxlib                       0.4.25+cuda12.cudnn89
keras                        3.0.5
libclang                     16.0.6
Markdown                     3.6
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
mdurl                        0.1.2
ml-dtypes                    0.3.2
namex                        0.0.7
numpy                        1.26.4
nvidia-cublas-cu12           12.4.2.65
nvidia-cuda-cupti-cu12       12.4.99
nvidia-cuda-nvcc-cu12        12.4.99
nvidia-cuda-nvrtc-cu12       12.4.99
nvidia-cuda-runtime-cu12     12.4.99
nvidia-cudnn-cu12            8.9.7.29
nvidia-cufft-cu12            11.2.0.44
nvidia-cusolver-cu12         11.6.0.99
nvidia-cusparse-cu12         12.3.0.142
nvidia-nccl-cu12             2.20.5
nvidia-nvjitlink-cu12        12.4.99
opensimplex                  0.4.5
opt-einsum                   3.3.0
optax                        0.2.1
packaging                    24.0
pillow                       10.2.0
pip                          24.0
protobuf                     4.25.3
Pygments                     2.17.2
requests                     2.31.0
rich                         13.7.1
ruamel.yaml                  0.18.6
ruamel.yaml.clib             0.2.8
scipy                        1.12.0
setuptools                   65.5.0
six                          1.16.0
tensorboard                  2.16.2
tensorboard-data-server      0.7.2
tensorflow-cpu               2.16.1
tensorflow-io-gcs-filesystem 0.36.0
tensorflow-probability       0.24.0
termcolor                    2.4.0
toolz                        0.12.1
typing_extensions            4.10.0
urllib3                      2.2.1
Werkzeug                     3.0.1
wheel                        0.38.4
wrapt                        1.16.0

**Comment by kennetms** [comment]
Error does not appear when using Python3.9.18.

**Comment by TL-Li** [comment]
You can also set the driver_parallel as False in the configs.yaml
