### ISSUE TITLE
How are online trajectories sampled?

### ISSUE THREAD

**Issue by edwhu** [danijar/dreamerv3#119]
Hi, thanks for the update! 

The paper states: 
> " We implement Dreamer using a uniform replay buffer with an online queue. Specifically, each minibatch is formed first from non-overlapping online trajectories and then filled up with uniformly sampled trajectories from the replay buffer."

I looked into the `replay.py` code to see how this is implemented, and have some confusion.
I see that the `online` flag is set to true,  and the sample function uses `popleft` to get the oldest samples in the queue.

I thought the "non-overlapping online trajectories" mentioned in the paper description are on-policy rollouts - wouldn't that mean we want to sample the most recent samples from the queue, since those are generated by the current policy? 

Or are the  "non-overlapping online trajectories" just the imagination rollouts?

https://github.com/danijar/dreamerv3/blob/1aac61b2217dcd0c7ee8718aa79bea76cefed360/embodied/replay/replay.py#L178-L192

**Comment by danijar** [comment]
We pop from the queue to fill as much of the batch as possible, and then fill remaining batch entries by uniform sampling from the buffer. So the queue is always very short (if not empty).
