### ISSUE TITLE
ImageDecoderResnet for non-standard image sizes

### ISSUE THREAD

**Issue by signalprime** [danijar/dreamerv3#12]
Thank you and your team for sharing this with the scientific community.  The significance of your work cannot be over-estimated: +9e9999 karma to you all, friend.

If we use an image of any size other than 32x32, we run into the [assertion error](https://github.com/danijar/dreamerv3/blob/main/dreamerv3/nets.py#L396).  Could we ask for a suggestion about how we might update [ImageDecoderResnet](https://github.com/danijar/dreamerv3/blob/main/dreamerv3/nets.py#L350) to handle alternative image resolutions?  Should we focus on the [Linear class](https://github.com/danijar/dreamerv3/blob/main/dreamerv3/nets.py#L562)?  

Thanks for any suggestions, and more than anything, thanks for the brilliant contribution

**Comment by danijar** [comment]
Hi @signalprime, thanks for the nice words!! 

By default, the networks are configured to work with any power of two, for example 32x32, 64x64 (the default), and 128x128. That's because the conv layers use stride 2 and downsample the input until it reaches 4x4, which is then flattened and fed into the dynamics model.

The downsampling size can be specified via `encoder.minres: 4` and `decoder.minres: 4`. The default of 4 works for resolutions that can be expressed as `2 * 2 * ... * 2 * 4`. You can change the two options to 6 to deal with resolutions that can be expressed as `2 * 2 * ... * 2 * 6`, such as 48x48 and 96x96.

**Comment by vtopiatech** [comment]
Hey @danijar thanks for this wonderful piece of work! Related to this issue, I was wondering how should we make it work with environments like gym's [VideoChess](https://gymnasium.farama.org/environments/atari/video_chess/#videochess) which have non-square resolutions, like in this case `(210, 160)`

I tried using `env = ResizeObservation(env, (64, 64))` but it seems it's not compatible with DreamerV3?

Got this error:
```bash
│ ~/chess-dreamerv3/.venv/lib/python3.11/site-packages/gym/wrappers/resize_observation.py:67 in observation |
│   66 │   │                                                                                       │
│ ❱ 67 │   │   observation = cv2.resize(                                                           │
│   68 │   │   │   observation, self.shape[::-1], interpolation=cv2.INTER_AREA                     │
│   69 │   │   )                                                                                   │
│   70 │   │   if observation.ndim == 2:                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'
```

**Comment by vtopiatech** [comment]
Update: seems like manually editing `~/.venv/lib/python3.11/site-packages/gym/wrappers/resize_observation.py` like below fixes this issue.

Default: `observation = cv2.resize(observation, self.shape[::-1], interpolation=cv2.INTER_AREA)`
Fixed: `observation = cv2.resize(observation**[0]**, self.shape[::-1], interpolation=cv2.INTER_AREA)`
