### ISSUE TITLE
Invalid syntax `segment = prob[*path]`

### ISSUE THREAD

**Issue by maxencefaldor** [danijar/dreamerv3#122]
I encounter an invalid syntax error because starred expressions are not valid within brackets at https://github.com/danijar/dreamerv3/blob/2411f7d136832378c0291c587cdbf2fca6506873/embodied/replay/selectors.py#L88

**Comment by swsychen** [comment]
I solved it by upgrading python to 3.11.

**Comment by danijar** [comment]
Updated the REAME to mention that Python 3.11+ is required now. If it's hard to upgrade, it's also easy to change the few places in the code to make it run on older Python versions but I don't have time to do that myself.
