### ISSUE TITLE
Question about integration of Plan2Explore

### ISSUE THREAD

**Issue by swsychen** [danijar/dreamerv3#127]
Hi, I'd like to integrate the Plan2Explore algorithm into the latest dreamerv3 repo. The original code of Plan2Explore in the dreamerv2 repo seems to differ quite a lot from the current layout of the dreamerv3. And the current usage of some advanced Jax features in JAXAgent seems quite complicated and I'm not sure which part of the code should I begin with first.

May I ask, do you have any advice on how to integrate the Plan2Explore?

Thank you very much.

**Comment by danijar** [comment]
Hi, we removed that from the code during cleanup but it should be quite easy to add back. You don't need to make any changes to `jaxagent.py`. Just add the ensemble network with a stop gradient to the model graph and include it in the optimizer, and then add the disagreement to the rewards?
