### ISSUE TITLE
Outdated README for custom environment and mlp_keys/cnn_keys

### ISSUE THREAD

**Issue by ThomasRochefortB** [danijar/dreamerv3#128]
Is it possible the README.MD file is out of date with the current update of DreamerV3? Especially this section:

`When running on custom environments, make sure to specify the observation keys the agent should be using via enc.simple.mlp_keys, enc.simple.cnn_keys, dec.simple.mlp_keys and dec.simple.cnn_keys.`

Do we still need to do this for custom environments?

I only see references to `enc.spaces` and `dec.spaces` in the configs.yaml file.

**Comment by danijar** [comment]
Thanks for pointing this out! It's now a bit simpler: `enc.spaces` and `dec.spaces` and the code determines whether to use the CNN or MLP based on dimensionality of the observations.

**Comment by ThomasRochefortB** [comment]
Thanks for the precision! Is it possible that by default, with the FromGym wrapper, both the encoder and the decoder will use all the observation spaces? Without specifying anything for `enc.spaces` and `dec.spaces`, I see when starting main.py:

Encoder: {'beta': (27,), 'design_variables': (48,), 'image': (64, 64, 3), 'n_steps_left': (1,), 'score': (1,), 'structure_strain_energy': (64, 64, 3), 'volume': (1,)}
Decoder: {'beta': (27,), 'design_variables': (48,), 'image': (64, 64, 3), 'n_steps_left': (1,), 'score': (1,), 'structure_strain_energy': (64, 64, 3), 'volume': (1,)}

Which corresponds to all of the observation spaces of my custom gym environment.

Looking at the FromGym wrapper I only see the 'image' observation though:
```
class FromGym(embodied.Env):

  def __init__(self, env, obs_key='image', act_key='action', **kwargs):
```
