### ISSUE TITLE
Why is the posterior being sampled for the policy during inference?

### ISSUE THREAD

**Issue by sai-prasanna** [danijar/dreamerv3#133]
In dreamerv2 the flag `mode=train` was passed to the posterior computation in `observe` to use the modes of the stochastic state. I notice now that we always sample. Is it intended or inconsequential?

https://github.com/danijar/dreamerv3/blob/29eb964e2918a3f4db04086f7f51b60388e97f3d/dreamerv3/agent.py#L129

**Comment by danijar** [comment]
It's intended because it's easier and still works quite well.
