### ISSUE TITLE
About running statistics

### ISSUE THREAD

**Issue by Warry98** [danijar/dreamerv3#153]
When computing moments (percentiles or others), shouldn't the statistics be weighted by the weights computed here to exclude the terminated trajectories in the calculation?
https://github.com/danijar/dreamerv3/blob/251910d04c9f38dd9dc385775bb0d6efa0e57a95/dreamerv3/agent.py#L301

**Comment by Warry98** [comment]
Hi there, any updates on this?

To clarify, the issue should be exacerbated when the imagination horizon is large and terminal states are present. In these cases, if the imagined trajectory terminates before reaching the end of the horizon, the percentiles (or other stats) may be computed using steps that have already terminated.

https://github.com/danijar/dreamerv3/blob/251910d04c9f38dd9dc385775bb0d6efa0e57a95/dreamerv3/agent.py#L313-L316

If I'm interpreting the code correctly, in extreme scenarios where the ratio of terminated steps to non-terminated steps within the imagination horizon is large, the terminated steps can dominate the statistics.

It would be great if someone could clarify this. Maybe it’s just an implementation detail that doesn't matter much in practice, or I may have overlooked whether it is already accounted for in the code.

Thanks in advance!

**Comment by danijar** [comment]
Good idea! We currently don't do this and it still works fine but it's possibly that that would improve performance.
