### ISSUE TITLE
Should `train_ratio` of Atari 200M be 128?

### ISSUE THREAD

**Issue by LYK-love** [danijar/dreamerv3#154]
Hi, I noticed that in the paper, the replay ratio for Atari 200M experiment is 32, and from my understanding, we have
```
replay_ratio / (action_repeat * batch_steps) ==  num of gradient steps / num of environment steps
```
where action_repeat=4, batch_steps=2^10. 

However, replay ratio is not directly defined in this repo. In `config.yaml`, I find `train_ratio` which is defined as, from what I believe,
```
train_ratio /  batch_steps ==  num of gradient steps / num of environment steps
```

So, we have
```
train_ratio (in code) == action_repeat * replay_ratio (in paper)
```
For Atari 200m, since action repeat is 4, and replay ratio, as reported in the paper, is 32 (see [here](https://github.com/danijar/dreamerv3/blob/main/dreamerv3/configs.yaml#L52)), so I think the `train_ratio` should be 128. But in the code it's set to be 32, which makes me confused.

**Comment by danijar** [comment]
The agent doesn't know about action repeat, that's only applied inside the environment and inside the logger.

**Comment by LYK-love** [comment]
> The agent doesn't know about action repeat, that's only applied inside the environment and inside the logger.

Thanks for your reply! So can you tell me the `train_ratio` value to reproduce the Atari 200M results in the DreamverV3 paper?

**Comment by danijar** [comment]
Yes, train ratio 32 is correct as in the code. The train ratios in the paper are also in terms of policy frames not agent frames.

**Comment by LYK-love** [comment]
> Yes, train ratio 32 is correct as in the code. The train ratios in the paper are also in terms of policy frames not agent frames.

I see. May I also ask about the correct `train_ratio` value for atari100k? Because in paper it's 128. while in code it's 256 (see [here](https://github.com/danijar/dreamerv3/blob/main/dreamerv3/configs.yaml#L216)).

**Comment by rsun0** [comment]
Others noted in #138 that the train ratio for atari100k should be 1024, instead of the 256 value set by the code in configs.yaml for atari100k. But I have no idea where they got 1024 from.
