### ISSUE TITLE
Why in your latest code no longer use backpropagation to update the policy, but use reinforce?

### ISSUE THREAD

**Issue by hdadong** [danijar/dreamerv3#168]
Hello danijar，I have been following dreamerv3,

What caused you to change it in this [commit](https://github.com/danijar/dreamerv3/commit/2411f7d136832378c0291c587cdbf2fca6506873#diff-b23bcbca1c263518b75b6bce4b40f6a96c8463c0732840da7f6dbbb22a0a6311)? Is it because backpropagation doesn't perform well in some environments? I'd really like to know the specific reasons, thank you for your reply.

The code is here:
https://github.com/danijar/dreamerv3/blob/main/dreamerv3/agent.py#L413

**Comment by danijar** [comment]
Backprop through the rollouts can be slightly faster for continuous control, but doesn't work that well for discrete actions where the dynamics aren't not smooth. Using reinforce everywhere works almost as well, simplifies things, and saves flops and memory. All the results in the ArXiv paper are using the version with reinforce.
