### ISSUE TITLE
Performance on simple gym environments

### ISSUE THREAD

**Issue by EdanToledo** [danijar/dreamerv3#23]
Hey Danijar, 

I am a big fan of the dreamer algorithms, especially this paper but I was wondering if you have any insight on why the world models seemingly can't be learnt for simple gym environments in my testing. I've been running this code base on Cartpole and Lunar lander (pixel observations) and whilst background information is learnt, the movement of the cart and spaceship are never included in the world models predictions. Additionally, the policy never learns to perform well. I am using the small model size. Is it possible that these environments observations are too simple or I am not training long enough (+2 hours but on a CPU only machine). Please let me know if you have any thoughts as to why this could be the case. Thanks so much.

**Comment by EdanToledo** [comment]
On a side note: do you use zero padded states at the beginning of each sequence observation when observing data for the world model loss function?

**Comment by danijar** [comment]
Hi, yes you'll need to train longer and need a decent GPU.
