### ISSUE TITLE
CUDA check failed with custom env

### ISSUE THREAD

**Issue by praveen-palanisamy** [danijar/dreamerv3#25]
## Issue Description
When training with a custom Gym env, there seems to be some dimension mismatch in the observation tensor batch OR some other issue (related to ninjax?) that causes a CUDNN crash with the following error:
```bash
F external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:632] Check failed: cudnnSetTensorNdDescriptor(handle_.get(), elem_type, nd, dims.data(), strides.data()) == CUDNN_STATUS_SUCCESS (9 vs. 0)batch_descriptor: {count: 1024 feature_map_count: 48 spatial: 259 259  value_min: 0.000000 value_max: 0.000000 layout: BatchYXDepth}
```
See attached [dreamerv3-train-crash.txt](https://github.com/danijar/dreamerv3/files/10894838/dreamerv3-train-crash.txt) for full log.
**Could you suggest a resolution or point to the code line/module that could cause the above?** Unfortunately, Python Debugger didn't produce any trace.
 ### Additional Notes
 1. Agent's model, actor & critic network are initialized with the correct dimensions based on the observation space
 2. Replay buffer prefill steps to gather the train dataset executes fine
 ## Steps to reproduce the error
 
Minimal changes to [example.py](https://github.com/danijar/dreamerv3/blob/main/example.py) to reproduce the above error:

1. Replace the following lines:

https://github.com/danijar/dreamerv3/blob/51556cd3ceaedf61d1528008878db6595193a01e/example.py#L35-L37

With

```python
    import gym
    import playwrightgym
    from embodied.envs import from_gym
    from gym.wrappers.resize_observation import ResizeObservation
    env = playwrightgym.playwright_env.PlaywrightEnv()
    env = ResizeObservation(env, (256, 256))
```
2. Install additional python env requirements:

```bash
python -m pip install playwrightgym playwright opencv-contrib-python && \
python -m playwright install
```
3. Run: `python example.py`

 Thanks in advance for your help!

**Comment by praveen-palanisamy** [comment]
Thanks for the response. Using `64 x 64` images did work. 
With `256x256` I didn't observe CUDA OOM. The memory utilization was <60% (after all the net params and the batch tensors were loaded and just before the crash). I am unable to debug/find the actual cause.

**Comment by danijar** [comment]
That's most likely a CUDA OOM from the activations of the forward/backward pass then. CUDA isn't very good at raising helpful error messages.
