### ISSUE TITLE
Out of memory error on cluster

### ISSUE THREAD

**Issue by jadkins99** [danijar/dreamerv3#47]
![Screenshot 2023-04-18 at 2 29 32 PM](https://user-images.githubusercontent.com/48653578/232898287-3c792039-c041-4f88-9fbd-f31a83a338c0.png)
I have been running DMLab Goals small & Crafter experiments on a cluster and after ~10 hours I get an out of memory error. I am allocating 32 GB of memory for the job. The error doesn't happen at a fixed time, so I don't believe that a forward pass through any of the network is the issue. Could there be some memory leak? Do you have any idea what could be causing this?

**Comment by danijar** [comment]
How many environment steps have you trained for? The replay buffer will keep increasing for the first 1M steps.

**Comment by jadkins99** [comment]
I have trained for ~29M environment steps.

**Comment by jadkins99** [comment]
This is plot of memory usage. Turns out I needed slightly more than 32GB sometimes.

![image](https://user-images.githubusercontent.com/48653578/233699898-82631476-2516-45cc-81e3-59c07517fb30.png)
