### ISSUE TITLE
Singularity and Atari

### ISSUE THREAD

**Issue by jadkins99** [danijar/dreamerv3#48]
I converted the Docker container to a singularity container for running on cluster. Most environments work. However, when I run Atari Breakout experiments, I get a libc6 version error. However, the version of libc6 that is required is incompatible with the Ubuntu base image of the DockerFile. Have you any experience running these experiments on a SLURM cluster with singularity?

**Comment by danijar** [comment]
I haven't, sorry. But if you get it to work, I'm sure some people would appreciate a PR.
