### ISSUE TITLE
Meaning of each row in the `report/openl_image` video

### ISSUE THREAD

**Issue by HHousen** [danijar/dreamerv3#50]
Here is the GIF I am referring to. A similar one is logged when training on the Crafter environment. This is the [BoxWorld environment](https://github.com/deepmind/pycolab/tree/master/pycolab/examples/research/box_world) from pycolab.

![new](https://user-images.githubusercontent.com/11785397/233802911-2237d3c5-de6b-43de-9722-89e87d30bd2b.gif)

The code that creates it is in https://github.com/danijar/dreamerv3/blob/main/dreamerv3/agent.py#L200.

Based on the image, it seems like something isn't working properly on this environment: The model solves the first task shown in the top row but then fails to solve the next task because the second row fails to update to match the new task (see second column from the right). The reward that is printed out is usually 11 (the maximum) but is occasionally 0 when the agent exhausts the number of permitted steps

Any suggestions of what I'm doing wrong or what I should change? Thanks!

**Comment by till2** [comment]
Hey, I think you misinterpreted the plot -- they both show the same task. Both the top and middle row are given 5 frames as context. Afterwards, the top row shows the agent acting in the actual environment. The middle row shows the agent acting in the learned world model (imagination) that simulates the environment.
And the bottom row shows the difference (delta map) between the episodes in the environment and model.
