### ISSUE TITLE
Expected FPS on V100?

### ISSUE THREAD

**Issue by MarcoMeter** [danijar/dreamerv3#54]
Hey @danijar 
thanks a lot for open sourcing DreamerV3!

I'm currently reproducing your crafter results and was wondering if 4.6 FPS sound right to you during training.
The training is executed on 32 cores and one V100 GPU. The log states that the GPU is used.
Give 4.6 FPS, it would take 25 days to achieve a training duration of 10M steps (I'm referring to Figure 6).

`python dreamerv3/train.py --logdir logdir/train --configs crafter --run.script train`

**Comment by danijar** [comment]
Hi, you can change the training ratio to collect 10M steps faster at the expense of less data-efficiency, e.g. `--run.train_ratio 16`.
