### ISSUE TITLE
Difference between model_loss and model_opt_loss

### ISSUE THREAD

**Issue by subho406** [danijar/dreamerv3#56]
Hey, 

I was just going through the logs for one of the runs generated using DreamerV3 and noticed that the code logs two different model losses (1) model_loss and (2) model_opt_loss. I found that the value of model_opt_loss is generally way higher than the model_loss for the Crafter environment.  I was wondering if you could explain me the differences between the two? If you could point me to the equations in the paper they refer to, that would be great. Thanks!

**Comment by danijar** [comment]
Hi, I think that's because of dynamic loss scaling that happens when you train in mixed precision (float16) mode.
