### ISSUE TITLE
BSuite Implementation

### ISSUE THREAD

**Issue by Snagnar** [danijar/dreamerv3#61]
Hi,

It seems like there is no implementation in the embodied package for running the bsuite experiments. The configuration exists in the configs.yaml but executing it fails since it bsuite is not specified in [the env dict in the training script](https://github.com/danijar/dreamerv3/blob/main/dreamerv3/train.py#L161-L172).

I suppose this only requires creating a class for BSuite in embodied/envs analog to the DMC environment specification. I will try to make a PR for this.

**Comment by swsychen** [comment]
> Hi,
> 
> It seems like there is no implementation in the embodied package for running the bsuite experiments. The configuration exists in the configs.yaml but executing it fails since it bsuite is not specified in [the env dict in the training script](https://github.com/danijar/dreamerv3/blob/main/dreamerv3/train.py#L161-L172).
> 
> I suppose this only requires creating a class for BSuite in embodied/envs analog to the DMC environment specification. I will try to make a PR for this.

May I ask, did you solve this?

**Comment by danijar** [comment]
Added bsuite env to the code :)
