### ISSUE TITLE
GRU has non-standard def?

### ISSUE THREAD

**Issue by Jogima-cyber** [danijar/dreamerv3#66]
Hi, I was wondering if there was a reason for using different formulas for the definition of the GRU? If I'm not mistaken, the standard formulas:
<img width="406" alt="Capture d’écran 2023-06-13 à 14 33 07" src="https://github.com/danijar/dreamerv3/assets/58483181/8348115a-27d1-4d84-b903-02576cb8ebe5">
and the ones used in this implementation: https://github.com/danijar/dreamerv3/blob/423291a9875bb9af43b6db7150aaa972ba889266/dreamerv3/nets.py#L131-L140
are different.

**Comment by danijar** [comment]
Hi, I think the version I'm using was designed by Nvidia for cuDNN. The motivation is that you compute all relevant quantities in a single matmul.

**Comment by Jogima-cyber** [comment]
Thanks for the answer!
