### ISSUE TITLE
Question about a potential error in the paper

### ISSUE THREAD

**Issue by till2** [danijar/dreamerv3#69]
Hi Danijar,

I wanted ask whether there is a negative sign missing in front of the $sg(R^\lambda_t)/\max(1,S)$ in eq. 11 in the D-V3 paper. I think the negative return (or advantage) should be minimized, right?

![image](https://github.com/danijar/dreamerv3/assets/89709351/6156bc2e-7100-4abf-b348-55aaae3ee772)

Best, Till

**Comment by danijar** [comment]
You're right, it'll be fixed in the next update.
