### ISSUE TITLE
Index issue in score function of vf?

### ISSUE THREAD

**Issue by Jogima-cyber** [danijar/dreamerv3#70]
Hi, I hope I'm not mistaken, but I think there is an index issue in the score function of the value function approximator:
If I understand everything correctly we want the prediction of the rewards of all the transitions, including the starting one, but not the last one:
<img width="909" alt="Capture d’écran 2023-06-20 à 17 30 39" src="https://github.com/danijar/dreamerv3/assets/58483181/3a84b0ab-a9e0-4a0b-b2e1-0e2907f7ebfe">
But it appears to me the implementation takes the predicted reward of all transitions including the last one but excluding the first one:
https://github.com/danijar/dreamerv3/blob/423291a9875bb9af43b6db7150aaa972ba889266/dreamerv3/agent.py#L360-L362
https://github.com/danijar/dreamerv3/blob/8fa35f83eee1ce7e10f3dee0b766587d0a713a60/dreamerv3/behaviors.py#L14
So maybe there is an index inversion somewhere in the code, but I didn't see one.
There is the same issue with the continuation predictor:
https://github.com/danijar/dreamerv3/blob/8fa35f83eee1ce7e10f3dee0b766587d0a713a60/dreamerv3/agent.py#L364

**Comment by Jogima-cyber** [comment]
Okay I've checked again and understood how it worked. No issue actually. Sorry about that.

**Comment by czp16** [comment]
Hi @Jogima-cyber , could you explain how it works? I'm still confused about the codes here. The codes here indicate that we should use `wm.heads['reward'](traj).mean()[1]` to compute the reward of h[0] and z[0] (the first deterministic and stochastic states in `traj`). 

Does this mean that reward head is computing $(h_{t+1}, z_{t+1}) \to r_t$ instead of $(h_t, z_t) \to r_t$?

**Comment by jren03** [comment]
Hi @czp16, if I am not mistaken from @danijar 's response on these two posts [[1](https://github.com/danijar/dreamerv3/issues/58), [2](https://github.com/danijar/dreamerv3/issues/14)], I think the notation is actually suggesting that the reward head predicts $(h_{t}, z_{t}) \rightarrow r_{t+1}$. I found the diagram in [[1](https://github.com/danijar/dreamerv3/issues/58)] to be pretty helpful.
