### ISSUE TITLE
[Question] Reference(s) for exploration behaviour?

### ISSUE THREAD

**Issue by IsaacSST** [danijar/dreamerv3#72]
Hi, just wondering if you have a reference for the exploration behaviour as implemented in the code? Since it's not discussed in the paper. As far as I can tell it's most similar to what's introduced in this paper: https://openreview.net/forum?id=OWZVD-l-ZrC, but not totally sure.

**Comment by danijar** [comment]
Do you mean [Plan2Explore](https://danijar.com/plan2explore)?
