### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by jadkins99** [danijar/dreamerv3#76]
Hi, when I attempt to run basic gym envs from the example script, there is a list index out of range error. Screenshots are from an attempt to run Pendulum-v1. 

<img width="1512" alt="Screenshot 2023-07-31 at 6 51 34 PM" src="https://github.com/danijar/dreamerv3/assets/48653578/16e6cc18-a4f8-47e9-b97d-897ea8e65c77">
<img width="877" alt="Screenshot 2023-07-31 at 6 51 31 PM" src="https://github.com/danijar/dreamerv3/assets/48653578/39012b00-c850-4d63-a337-85241678b506">

**Comment by danijar** [comment]
Hi, thanks for opening an issue about this. Curious what caused it and how you fixed it?

**Comment by jesuspc** [comment]
I had the same problem when trying to reuse `example.py` with a non-image custom env. It went away after commenting out the following lines:

```
  #'encoder.mlp_keys': '$^',
  #'decoder.mlp_keys': '$^',
  #'encoder.cnn_keys': 'image',
  #'decoder.cnn_keys': 'image',
```
