### ISSUE TITLE
Offline Training

### ISSUE THREAD

**Issue by mrsamsami** [danijar/dreamerv3#80]
Hey, I want to express my gratitude for this fantastic code repo!

I'm currently seeking advice on the most straightforward approach to training an online agent, gathering a dataset, and subsequently training an offline agent with the dataset. I've been unable to locate the "offline mode" for training. Is it possibly embedded somewhere in the codebase?

**Comment by danijar** [comment]
Hi, there is no purely offline training implemented, although you could just set the train ratio to a very large number. It's also quite straightforward to adapt one of the run scripts, for example `run/train_eval.py` or similar. Hope that helps a little bit.
