### ISSUE TITLE
[Question] How is symlog used in training?

### ISSUE THREAD

**Issue by ahan98** [danijar/dreamerv3#83]
Hi, I had some conceptual questions about the role of symlog, specifically for training the decoder.

In the code, it looks like [SymlogDist.log_prob()](https://github.com/danijar/dreamerv3/blob/8fa35f83eee1ce7e10f3dee0b766587d0a713a60/dreamerv3/jaxutils.py#L141) computes the MSE of the symlog-transformed target, as described in equation 1 of the paper.

So, _unlike_ the distributions included in `torch.distributions`, `log_prob` in this case is really a custom score, rather than the literal log likelihood, right? Then, in equation 5, does that mean the first term of the prediction loss is this symlog MSE, rather than an actual log likelihood?

I'm also confused about what the decoder output means. For example, in DreamerV2, "The image predictor outputs the mean of a diagonal Gaussian likelihood with unit variance" ([page 4](https://arxiv.org/pdf/2010.02193.pdf), in the paragraph on "Distributions").

Unlike DreamerV2, it seems like the decoder in DreamerV3 is no longer doing PDF estimation (especially since symlog is only for [non-image](https://github.com/danijar/dreamerv3/issues/73#issue-1807690860) vector observations), but rather learning to regress `symlog(x_t)` given `h_t, z_t`. Am I understanding this correctly?

Thanks

**Comment by danijar** [comment]
Hi, yes the image decoder just uses MSE and the vector decoder uses MSE in symlog space. The MSE gradient is equivalent to that of a diagonal Gaussian logprob.
