### ISSUE TITLE
Scaling encoder and decoder MLP sizes?

### ISSUE THREAD

**Issue by thomasbi1** [danijar/dreamerv3#86]
Hi

As far as I can tell, the different model sizes keep the number of `mlp_layers` and `mlp_units` in the encoder/decoder constant and don't change them (as `.*\.units` and `.*\.layers` do not match `mlp_layers` and `mlp_units`). Is there a reason for this? Is it because the MLP layers in the encoder/decoder don't affect the model size much?

**Comment by danijar** [comment]
Good point, they should probably also be changed. There was no specific reason for this, just an oversight. The scaling experiments in the paper happen to be on image-only environments, so they aren't affected.

**Comment by thomasbi1** [comment]
I see, thanks for clarifying! Do you know if the curves from the DMC Proprio tasks (with model size S) in the paper correspond to the models as in this implementation, or were the mlp_layers scaled for the paper?

**Comment by danijar** [comment]
It corresponds to this implementation, i.e. the MLPs for reward, continue, actor, and critic were scaled but vector encoder and vector decoder were not.
