### ISSUE TITLE
Scaling laws in low-data regime

### ISSUE THREAD

**Issue by bseveren** [danijar/dreamerv3#94]
Hi,
First of all thank you for this magnificent work!

We're doing tests with the dreamerv3 repo in a low-data regime (with human feedback). The scaling laws for low-data are a bit confusing to me currently. You added these graphs showing that bigger models do better when tens of millions of frames are available (but unclear for the 400K frame case):

![image](https://github.com/danijar/dreamerv3/assets/5585752/ac3b00ac-1144-4515-9d4d-937b697c45dd)

Surprisingly you chose small models for the low-data regime benchmarks:

![image](https://github.com/danijar/dreamerv3/assets/5585752/9e120121-5b86-434a-92aa-15340ad7cb38)

Did you test e.g. Atari100K with bigger models? If yes, are bigger models worse (or just not better)? If you did not test them with bigger models, what was the reason (e.g. related to the theory of [Deep double descent](https://openai.com/research/deep-double-descent))?

**Comment by danijar** [comment]
Hi, good observation. I'm using the bigger models on Atari100k in the updated paper. But there is a limit at which, when the task is really simple and the model really large, increasing model size further does not help. Then, it can make sense to use a smaller model for speed up wall clock time and thus iterate faster.

![image](https://github.com/danijar/dreamerv3/assets/2111293/865ef6d3-8e06-4105-9b50-6d14aa5c72a5)
